# Config file for automatic testing at travis-ci.com
#sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install -r requirements_plotting.txt
  - pip install coverage
  - pip install codecov
#script: python -m unittest discover tests
script: coverage run -m unittest discover tests
after_success:
  - codecov