# This environment allows some packages to be managed by conda.
# This is not necessary on unix environment, but offers easy venvs on windows

name: impact_conda_venv
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas